/**
 * THIS WAS GENERATED BY CLAUDE AS SOMETHING FOR ME TO TEST WITH WHILE
 * LEARNING TO DEVELOP A CYPRESS TEST SUITE
 *
 * Starts mock-ankiconnect.js and app.js, waits for the app to come up, then
 * runs Cypress against them. Pass --open to launch the interactive runner
 * instead of a headless run. Both servers are killed when Cypress exits.
 *
 * Usage:
 *   node scripts/run-e2e.js          # cypress run
 *   node scripts/run-e2e.js --open   # cypress open
 */

const { spawn } = require("child_process");
const http = require("http");
const path = require("path");

const root = path.join(__dirname, "..");
const open = process.argv.includes("--open");

function waitForServer(url, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  return new Promise((resolve, reject) => {
    (function poll() {
      http
        .get(url, (res) => {
          res.resume();
          resolve();
        })
        .on("error", () => {
          if (Date.now() > deadline) {
            reject(new Error(`Timed out waiting for ${url}`));
          } else {
            setTimeout(poll, 200);
          }
        });
    })();
  });
}

async function main() {
  const mock = spawn("node", ["mock-ankiconnect.js"], { cwd: root, stdio: "inherit" });
  const app = spawn("node", ["app.js"], {
    cwd: root,
    stdio: "inherit",
    env: { ...process.env, ANKICONNECT_URL: "http://localhost:8765" },
  });

  const cleanup = () => {
    mock.kill();
    app.kill();
  };

  try {
    await waitForServer("http://localhost:8765", 5000);
    await waitForServer("http://localhost:3000", 5000);
  } catch (err) {
    console.error(err.message);
    cleanup();
    process.exit(1);
  }

  const cypressArgs = open ? ["open"] : ["run"];
  const cypress = spawn("npx", ["cypress", ...cypressArgs], { cwd: root, stdio: "inherit" });

  cypress.on("exit", (code) => {
    cleanup();
    process.exit(code === null ? 1 : code);
  });
}

main();
